In [1]:
import numpy as np

#1

In [3]:
temperature=np.array([25,28,31,35,38,27,33,40])
#a
new_vect=temperature+2
print(new_vect)

[27 30 33 37 40 29 35 42]


In [5]:
#b
fah=((9/5)*new_vect) + 32
print(fah)

[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]


In [7]:
#c
print(new_vect[new_vect>32])

[33 37 40 35 42]


In [8]:
#d
print(np.sum(new_vect>32))

5


In [34]:
#e
print("Vectorization allows operations to be performed on an entire NumPy array at once without explicitly using a loop, making computations faster and more concise. Boolean indexing allows elements satisfying a condition to be selected directly. Together, they make array processing more efficient, readable, and convenient than explicitly iterating through every element.")

Vectorization allows operations to be performed on an entire NumPy array at once without explicitly using a loop, making computations faster and more concise. Boolean indexing allows elements satisfying a condition to be selected directly. Together, they make array processing more efficient, readable, and convenient than explicitly iterating through every element.


#2

In [11]:
steps=np.array([[5000,6200,7100],[8000,7500,9000],[4500,5100,4800],[9000,8500,9500]])
#a
print(np.sum(steps))
#b
print(np.mean(steps))
#c
print(np.max(steps))
print(np.min(steps))
#d
print(np.sum(steps,axis=0))
#e
print(np.sum(steps,axis=1))
#f
maxp=np.unravel_index(np.argmax(steps),steps.shape)
print(maxp)

84200
7016.666666666667
9500
4500
[26500 27300 30400]
[18300 24500 14400 27000]
(np.int64(3), np.int64(2))


#3

In [14]:
#a
original=np.array([1,2,3,4,5,6])
#b
subset=original[1:5]
print(subset)
#c
subset[0]=999
print(original)
print(subset)
#d
copied=original[1:5].copy()
copied[0]=500
print(original)
print(copied)


[2 3 4 5]
[  1 999   3   4   5   6]
[999   3   4   5]
[  1 999   3   4   5   6]
[500   3   4   5]


In [24]:
#e
arr=np.arange(1,13).reshape(3,4)
#f
print(arr[0,:])
print(arr[-1,:])
print(arr[:,1])
print(arr[0:2,1:3])
#g
flat=arr.flatten()
rav=arr.ravel()
#h
rav[0]=1000
print(rav)
print(arr)
#i
flat[0]=2000
print(flat)
print(arr)
#j
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[2 3]
 [6 7]]
[1000    2    3    4    5    6    7    8    9   10   11   12]
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
[2000    2    3    4    5    6    7    8    9   10   11   12]
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
(3, 4)
2
12
int64


#4

In [32]:
X=np.array([[6,70,3],[5,50,6],[8,80,2],[4,30,8]])
y=np.array([40,65,30,85])
#a
print(X.shape)
print(X.ndim)
#b
trans=X.T
print(trans)
#c
prod=X.T @ X
print(prod)
#d
inv=np.linalg.inv(prod)
print(inv)
#e
OLS=inv @ X.T @ y
print(OLS)
#f
print(OLS[0]," Sleep Coeff")
print(OLS[1]," Activity Coeff")
print(OLS[2]," Stress Coeff")
#g
new_user=np.array([5,40,7])
pred=new_user @ OLS
print(pred)

(4, 3)
2
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
[-0.15921454  0.14083853 10.06302242]
-0.15921454159483517  Sleep Coeff
0.1408385299190522  Activity Coeff
10.063022422714608  Stress Coeff
75.27862544779018
