In [1]:
import numpy as np

#1

In [2]:
arr1=np.array([1,2,3,4,5])
#a
print(arr1+2)

[3 4 5 6 7]


In [3]:
#b
print(arr1*3)

[ 3  6  9 12 15]


In [4]:
#c
print(arr1/2)

[0.5 1.  1.5 2.  2.5]


#2

In [5]:
#a
arr=np.array([1,2,3,6,4,5])
rev=arr[::-1]
print(rev)

[5 4 6 3 2 1]


In [8]:
#b
x=np.array([1,2,3,4,5,1,2,1,1,1])
val,cnts=np.unique(x,return_counts=True)
mostf=val[np.argmax(cnts)]
idx=np.where(x==mostf)
print(mostf)
print(idx)

y=np.array([1,1,1,2,3,4,2,4,3,3])
val1,cnts1=np.unique(y,return_counts=True)
mostf1=val1[np.argmax(cnts1)]
idx1=np.where(y==mostf1)
print(mostf1)
print(idx1)



1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


#3

In [10]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
#a
print(arr[0,1])
print(arr[2,0])

20
70


#4

In [16]:
Prerna=np.linspace(10,100,25)
print(Prerna)
print(Prerna.ndim)
print(Prerna.shape)
print(Prerna.size)
print(Prerna.dtype)
print(Prerna.nbytes)
trans=Prerna.reshape(25,1)
print(trans)
transT=Prerna.T
print(transT)
print(Prerna.reshape(1,25).T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


#5

In [20]:
ucs420_Prerna=np.array([[10,20,30,30],[50,60,70,80],[90,15,20,35]])
print(np.mean(ucs420_Prerna))
print(np.median(ucs420_Prerna))
print(np.max(ucs420_Prerna))
print(np.min(ucs420_Prerna))
print(np.unique(ucs420_Prerna))
reshaped_ucs420_Prerna=ucs420_Prerna.reshape(4,3)
print(reshaped_ucs420_Prerna)
resized_ucs420_Prerna=np.resize(ucs420_Prerna,new_shape=(2,3))


42.5
32.5
90
10
[10 15 20 30 35 50 60 70 80 90]
[[10 20 30]
 [30 50 60]
 [70 80 90]
 [15 20 35]]
